const paddingSizeList = [
  { value: "p-0", text: "0" },
  { value: "p-0.5", text: "0.125rem" },
  { value: "p-2", text: "0.5rem" },
  { value: "p-2.5", text: "0.625rem" },
  { value: "p-3", text: "0.75rem" },
  { value: "p-3.5", text: "0.875rem" },
  { value: "p-4", text: "1rem" },
  { value: "p-5", text: "1.25rem" },
  { value: "p-6", text: "1.5rem" },
  { value: "p-7", text: "1.75rem" },
  { value: "p-8", text: "2rem" },
  { value: "p-9", text: "2.25rem" },
  { value: "p-10", text: "2.5rem" },
  { value: "p-11", text: "2.75rem" },
  { value: "p-12", text: "3rem" },
  { value: "p-14", text: "3.5rem" },
  { value: "p-16", text: "4rem" },
  { value: "p-20", text: "5rem" },
  { value: "p-24", text: "6rem" },
  { value: "p-28", text: "7rem" },
  { value: "p-32", text: "8rem" },
  { value: "p-36", text: "9rem" },
  { value: "p-40", text: "10rem" },
  { value: "p-44", text: "11rem" },
  { value: "p-48", text: "12rem" },
  { value: "p-52", text: "13rem" },
  { value: "p-56", text: "14rem" },
  { value: "p-60", text: "15rem" },
  { value: "p-64", text: "16rem" },
  { value: "p-72", text: "18rem" },
  { value: "p-80", text: "20rem" },
  { value: "p-96", text: "24rem" },
];

const paddingLeft = [
  { value: "pl-0", text: "0" },
  { value: "pl-0.5", text: "0.125rem" },
  { value: "pl-2", text: "0.5rem" },
  { value: "pl-2.5", text: "0.625rem" },
  { value: "pl-3", text: "0.75rem" },
  { value: "pl-3.5", text: "0.875rem" },
  { value: "pl-4", text: "1rem" },
  { value: "pl-5", text: "1.25rem" },
  { value: "pl-6", text: "1.5rem" },
  { value: "pl-7", text: "1.75rem" },
  { value: "pl-8", text: "2rem" },
  { value: "pl-9", text: "2.25rem" },
  { value: "pl-10", text: "2.5rem" },
  { value: "pl-11", text: "2.75rem" },
  { value: "pl-12", text: "3rem" },
  { value: "pl-14", text: "3.5rem" },
  { value: "pl-16", text: "4rem" },
  { value: "pl-20", text: "5rem" },
  { value: "pl-24", text: "6rem" },
  { value: "pl-28", text: "7rem" },
  { value: "pl-32", text: "8rem" },
  { value: "pl-36", text: "9rem" },
  { value: "pl-40", text: "10rem" },
  { value: "pl-44", text: "11rem" },
  { value: "pl-48", text: "12rem" },
  { value: "pl-52", text: "13rem" },
  { value: "pl-56", text: "14rem" },
  { value: "pl-60", text: "15rem" },
  { value: "pl-64", text: "16rem" },
  { value: "pl-72", text: "18rem" },
  { value: "pl-80", text: "20rem" },
  { value: "pl-96", text: "24rem" },
];

const paddingRight = [
  { value: "pr-0", text: "0" },
  { value: "pr-0.5", text: "0.125rem" },
  { value: "pr-2", text: "0.5rem" },
  { value: "pr-2.5", text: "0.625rem" },
  { value: "pr-3", text: "0.75rem" },
  { value: "pr-3.5", text: "0.875rem" },
  { value: "pr-4", text: "1rem" },
  { value: "pr-5", text: "1.25rem" },
  { value: "pr-6", text: "1.5rem" },
  { value: "pr-7", text: "1.75rem" },
  { value: "pr-8", text: "2rem" },
  { value: "pr-9", text: "2.25rem" },
  { value: "pr-10", text: "2.5rem" },
  { value: "pr-11", text: "2.75rem" },
  { value: "pr-12", text: "3rem" },
  { value: "pr-14", text: "3.5rem" },
  { value: "pr-16", text: "4rem" },
  { value: "pr-20", text: "5rem" },
  { value: "pr-24", text: "6rem" },
  { value: "pr-28", text: "7rem" },
  { value: "pr-32", text: "8rem" },
  { value: "pr-36", text: "9rem" },
  { value: "pr-40", text: "10rem" },
  { value: "pr-44", text: "11rem" },
  { value: "pr-48", text: "12rem" },
  { value: "pr-52", text: "13rem" },
  { value: "pr-56", text: "14rem" },
  { value: "pr-60", text: "15rem" },
  { value: "pr-64", text: "16rem" },
  { value: "pr-72", text: "18rem" },
  { value: "pr-80", text: "20rem" },
  { value: "pr-96", text: "24rem" },
];

const paddingTop = [
  { value: "pt-0", text: "0" },
  { value: "pt-0.5", text: "0.125rem" },
  { value: "pt-2", text: "0.5rem" },
  { value: "pt-2.5", text: "0.625rem" },
  { value: "pt-3", text: "0.75rem" },
  { value: "pt-3.5", text: "0.875rem" },
  { value: "pt-4", text: "1rem" },
  { value: "pt-5", text: "1.25rem" },
  { value: "pt-6", text: "1.5rem" },
  { value: "pt-7", text: "1.75rem" },
  { value: "pt-8", text: "2rem" },
  { value: "pt-9", text: "2.25rem" },
  { value: "pt-10", text: "2.5rem" },
  { value: "pt-11", text: "2.75rem" },
  { value: "pt-12", text: "3rem" },
  { value: "pt-14", text: "3.5rem" },
  { value: "pt-16", text: "4rem" },
  { value: "pt-20", text: "5rem" },
  { value: "pt-24", text: "6rem" },
  { value: "pt-28", text: "7rem" },
  { value: "pt-32", text: "8rem" },
  { value: "pt-36", text: "9rem" },
  { value: "pt-40", text: "10rem" },
  { value: "pt-44", text: "11rem" },
  { value: "pt-48", text: "12rem" },
  { value: "pt-52", text: "13rem" },
  { value: "pt-56", text: "14rem" },
  { value: "pt-60", text: "15rem" },
  { value: "pt-64", text: "16rem" },
  { value: "pt-72", text: "18rem" },
  { value: "pt-80", text: "20rem" },
  { value: "pt-96", text: "24rem" },
];

const paddingBottom = [
  { value: "pb-0", text: "0" },
  { value: "pb-0.5", text: "0.125rem" },
  { value: "pb-2", text: "0.5rem" },
  { value: "pb-2.5", text: "0.625rem" },
  { value: "pb-3", text: "0.75rem" },
  { value: "pb-3.5", text: "0.875rem" },
  { value: "pb-4", text: "1rem" },
  { value: "pb-5", text: "1.25rem" },
  { value: "pb-6", text: "1.5rem" },
  { value: "pb-7", text: "1.75rem" },
  { value: "pb-8", text: "2rem" },
  { value: "pb-9", text: "2.25rem" },
  { value: "pb-10", text: "2.5rem" },
  { value: "pb-11", text: "2.75rem" },
  { value: "pb-12", text: "3rem" },
  { value: "pb-14", text: "3.5rem" },
  { value: "pb-16", text: "4rem" },
  { value: "pb-20", text: "5rem" },
  { value: "pb-24", text: "6rem" },
  { value: "pb-28", text: "7rem" },
  { value: "pb-32", text: "8rem" },
  { value: "pb-36", text: "9rem" },
  { value: "pb-40", text: "10rem" },
  { value: "pb-44", text: "11rem" },
  { value: "pb-48", text: "12rem" },
  { value: "pb-52", text: "13rem" },
  { value: "pb-56", text: "14rem" },
  { value: "pb-60", text: "15rem" },
  { value: "pb-64", text: "16rem" },
  { value: "pb-72", text: "18rem" },
  { value: "pb-80", text: "20rem" },
  { value: "pb-96", text: "24rem" },
];

export const paddingSizeLists = [
  // { id: 1, list: paddingSizeList },
  { id: "pl", list: paddingLeft, heading: "Left" },
  { id: "pr", list: paddingRight, heading: "Right" },
  { id: "pb", list: paddingBottom, heading: "Bottom" },
  { id: "pt", list: paddingTop, heading: "Top" },
];
