export const textSizeList = [
  { value: "text-xs", text: "Minor" },
  { value: "text-sm", text: "Small" },
  { value: "text-base", text: "Normal" },
  { value: "text-lg", text: "Large" },
  { value: "text-xl", text: "XLarge" },
  { value: "text-2xl", text: "2XLarge" },
  { value: "text-3xl", text: "3XLarge" },
  { value: "text-4xl", text: "4XLarge" },
  { value: "text-5xl", text: "5XLarge" },
  { value: "text-6xl", text: "6XLarge" },
  { value: "text-7xl", text: "7XLarge" },
  { value: "text-8xl", text: "8XLarge" },
  { value: "text-9xl", text: "9XLarge" },
];
